import type { PropsWithChildren } from 'react'
import Head from 'next/head'
import s from './PageTemplate.module.scss'

interface PageTemplateProps extends PropsWithChildren { }

export function PageTemplate(p: PageTemplateProps) {
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div className={s['PageTemplate']}>
                {p.children}
            </div>
        </main>
    </>
}
